apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: pasec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/parsec:simlarge
        name: parsecferret
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./bin/parsecmgmt -a run -p ferret -i simlarge -n 1"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "parsec"
