apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-x264
  labels:
    name: parsec-x264
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_x264
        name: parsec-x264
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "./run -a run -S parsec -p x264 -i native -n 1"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "parsec"
